### ISSUE TITLE
运行后如下报错

### ISSUE THREAD

**Issue by sayri23** [Pmx990/Mirai-Steam-Plugin#1]
![image](https://user-images.githubusercontent.com/62638560/123109829-252b0700-d46e-11eb-8c25-fe5789e31483.png)

**Comment by Pmx990** [comment]
请参考mirai官方论坛的[帖子](https://mirai.mamoe.net/topic/323/mirai%E6%9B%B4%E6%96%B0%E5%88%B02-7m1%E5%90%8Emirai-api-http%E6%8F%92%E4%BB%B6%E6%97%A0%E6%B3%95%E4%BD%BF%E7%94%A8?_=1624471850975) 

这是因为最新版的mirai和http依赖打架造成的，可以等待mirai的后续修复或者先使用旧版本。

**Comment by sayri23** [comment]
好的
